
package fr.protogen.communication.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import fr.protogen.engine.utils.ProtogenParameters;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ComServiceService", targetNamespace = "http://serviceweb.apiCom.web.phoenix.fr/", wsdlLocation = ProtogenParameters.APPLICATION+"/comwebservice/comService?wsdl")
public class ComServiceService
    extends Service
{

    private final static URL COMSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException COMSERVICESERVICE_EXCEPTION;
    private final static QName COMSERVICESERVICE_QNAME = new QName("http://serviceweb.apiCom.web.phoenix.fr/", "ComServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(ProtogenParameters.APPLICATION+"/comwebservice/comService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COMSERVICESERVICE_WSDL_LOCATION = url;
        COMSERVICESERVICE_EXCEPTION = e;
    }

    public ComServiceService() {
        super(__getWsdlLocation(), COMSERVICESERVICE_QNAME);
    }
/*
    public ComServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COMSERVICESERVICE_QNAME, features);
    }
*/
    public ComServiceService(URL wsdlLocation) {
        super(wsdlLocation, COMSERVICESERVICE_QNAME);
    }
/*
    public ComServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COMSERVICESERVICE_QNAME, features);
    }
*/
    public ComServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }
/*
    public ComServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }
*/
    /**
     * 
     * @return
     *     returns ComService
     */
    @WebEndpoint(name = "ComServicePort")
    public ComService getComServicePort() {
        return super.getPort(new QName("http://serviceweb.apiCom.web.phoenix.fr/", "ComServicePort"), ComService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ComService
     */
    @WebEndpoint(name = "ComServicePort")
    public ComService getComServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceweb.apiCom.web.phoenix.fr/", "ComServicePort"), ComService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COMSERVICESERVICE_EXCEPTION!= null) {
            throw COMSERVICESERVICE_EXCEPTION;
        }
        return COMSERVICESERVICE_WSDL_LOCATION;
    }

}
