
package fr.protogen.communication.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ComServiceFax", targetNamespace = "http://serviceweb.apiCom.web.phoenix.fr/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ComServiceFax {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    public void envoyerfaxerdifferer(
        @WebParam(name = "arg0", partName = "arg0")
        StringArray arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        XMLGregorianCalendar arg2);

    /**
     * 
     * @return
     *     returns client.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    public StringArray formatfaxvalid();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String getMessageEtatFax();

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    public void envoyerfaxer(
        @WebParam(name = "arg0", partName = "arg0")
        StringArray arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1)
        throws Exception_Exception
    ;

}
