
package fr.protogen.communication.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import fr.protogen.engine.utils.ProtogenParameters;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ComServiceFaxService", targetNamespace = "http://serviceweb.apiCom.web.phoenix.fr/", wsdlLocation = ProtogenParameters.APPLICATION+"/apiservice/comServiceFax?wsdl")
public class ComServiceFaxService
    extends Service
{

    private final static URL COMSERVICEFAXSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(fr.protogen.communication.client.ComServiceFaxService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = fr.protogen.communication.client.ComServiceFaxService.class.getResource(".");
            url = new URL(baseUrl, ProtogenParameters.APPLICATION+"/apiservice/comServiceFax?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/apiservice/comServiceFax?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        COMSERVICEFAXSERVICE_WSDL_LOCATION = url;
    }

    public ComServiceFaxService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ComServiceFaxService() {
        super(COMSERVICEFAXSERVICE_WSDL_LOCATION, new QName("http://serviceweb.apiCom.web.phoenix.fr/", "ComServiceFaxService"));
    }

    /**
     * 
     * @return
     *     returns ComServiceFax
     */
    @WebEndpoint(name = "ComServiceFaxPort")
    public ComServiceFax getComServiceFaxPort() {
        return super.getPort(new QName("http://serviceweb.apiCom.web.phoenix.fr/", "ComServiceFaxPort"), ComServiceFax.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ComServiceFax
     */
    @WebEndpoint(name = "ComServiceFaxPort")
    public ComServiceFax getComServiceFaxPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceweb.apiCom.web.phoenix.fr/", "ComServiceFaxPort"), ComServiceFax.class, features);
    }

}
