
package fr.protogen.communication.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ComService", targetNamespace = "http://serviceweb.apiCom.web.phoenix.fr/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ComService {


    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://serviceweb.apiCom.web.phoenix.fr/ComService/envoyerfaxerRequest", output = "http://serviceweb.apiCom.web.phoenix.fr/ComService/envoyerfaxerResponse")
    public void envoyerfaxer(
        @WebParam(name = "arg0", partName = "arg0")
        StringArray arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://serviceweb.apiCom.web.phoenix.fr/ComService/getMessageEtatFaxRequest", output = "http://serviceweb.apiCom.web.phoenix.fr/ComService/getMessageEtatFaxResponse")
    public String getMessageEtatFax();

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://serviceweb.apiCom.web.phoenix.fr/ComService/envoyermailacfileRequest", output = "http://serviceweb.apiCom.web.phoenix.fr/ComService/envoyermailacfileResponse")
    public void envoyermailacfile(
        @WebParam(name = "arg0", partName = "arg0")
        StringArray arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://serviceweb.apiCom.web.phoenix.fr/ComService/envoyermailRequest", output = "http://serviceweb.apiCom.web.phoenix.fr/ComService/envoyermailResponse")
    public void envoyermail(
        @WebParam(name = "arg0", partName = "arg0")
        StringArray arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://serviceweb.apiCom.web.phoenix.fr/ComService/envoyerSMSRequest", output = "http://serviceweb.apiCom.web.phoenix.fr/ComService/envoyerSMSResponse")
    public void envoyerSMS(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://serviceweb.apiCom.web.phoenix.fr/ComService/appellerRequest", output = "http://serviceweb.apiCom.web.phoenix.fr/ComService/appellerResponse")
    public void appeller(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     */
    @WebMethod
    @Action(input = "http://serviceweb.apiCom.web.phoenix.fr/ComService/decrocherRequest", output = "http://serviceweb.apiCom.web.phoenix.fr/ComService/decrocherResponse")
    public void decrocher();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://serviceweb.apiCom.web.phoenix.fr/ComService/getMessageEtatVoipRequest", output = "http://serviceweb.apiCom.web.phoenix.fr/ComService/getMessageEtatVoipResponse")
    public String getMessageEtatVoip();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://serviceweb.apiCom.web.phoenix.fr/ComService/getMessageEtatSMSRequest", output = "http://serviceweb.apiCom.web.phoenix.fr/ComService/getMessageEtatSMSResponse")
    public String getMessageEtatSMS();

}
