package fr.protogen.masterdata.model;

// Generated 12 oct. 2012 16:40:54 by Hibernate Tools 3.4.0.CR1

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CActionbutton generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "c_actionbutton", schema = "public")
public class CActionbutton implements java.io.Serializable {

	private int id;
	private CWindow CWindow;
	private MAction MAction;
	private String title;
	private List<ButtonParameter> listParam;
	private String parameters;
	private CDocumentbutton boundDocument;
	private boolean isBound;
	private boolean parametered;
	private String description;
	private boolean visible=true;

	public CActionbutton() {
	}

	public CActionbutton(int id, CWindow CWindow, String title) {
		this.id = id;
		this.CWindow = CWindow;
		this.title = title;
	}

	public CActionbutton(int id, CWindow CWindow, MAction MAction, String title) {
		this.id = id;
		this.CWindow = CWindow;
		this.MAction = MAction;
		this.title = title;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_window", nullable = false)
	public CWindow getCWindow() {
		return this.CWindow;
	}

	public void setCWindow(CWindow CWindow) {
		this.CWindow = CWindow;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_action")
	public MAction getMAction() {
		return this.MAction;
	}

	public void setMAction(MAction MAction) {
		this.MAction = MAction;
	}

	@Column(name = "title", nullable = false, length = 128)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public List<ButtonParameter> getListParam() {
		return listParam;
	}

	public void setListParam(List<ButtonParameter> listParam) {
		this.listParam = listParam;
	}

	public String getParameters() {
		return parameters;
	}

	public void setParameters(String parameters) {
		this.parameters = parameters;
	}

	public CDocumentbutton getBoundDocument() {
		return boundDocument;
	}

	public void setBoundDocument(CDocumentbutton boundDocument) {
		this.boundDocument = boundDocument;
	}

	public boolean isBound() {
		return isBound;
	}

	public void setBound(boolean isBound) {
		this.isBound = isBound;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public boolean isParametered() {
		return parametered;
	}

	public void setParametered(boolean parametered) {
		this.parametered = parametered;
	}

	public boolean isVisible() {
		return visible;
	}

	public void setVisible(boolean visible) {
		this.visible = visible;
	}

	

}
