package fr.protogen.masterdata.model;

// Generated 12 oct. 2012 16:40:54 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CAttribute generated by hbm2java
 */
@Entity
@Table(name = "c_attribute", schema = "public")
public class CAttribute implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private CAttributetype CAttributetype;
	private String dataReference;
	private boolean visible;
	private Set<CWindow> CWindows = new HashSet<CWindow>(0);
	private CBusinessClass entity = new CBusinessClass();
	private String attribute;
	private boolean isKeyAttribute = false;
	private boolean isReference = false;
	private boolean isMandatory;
	private String dtoValue;
	private boolean calculated=false;
	private String formula;
	private String typeLabel;
	private String description;
	private boolean multiple;
	private int dispalyOrder;
	private boolean isAutoValue;
	private boolean requiresValidation;
	private String validationFormula;
	private String fileName;
	private String fileExtension;
	private boolean rappel;	
	private boolean indirectReference;
	private boolean indirectMtmKey;
	private boolean indirectMtmValue;
	private int indirectFunction;
	private boolean filterEnabled;
	private String defaultValue="";
	private boolean conditionalLayout=false;
	private String lockLabel;
	private String unlockLabel;
	private boolean lockState;
	private boolean regular;
	private String regexp;
	private String regexpMessage;
	private boolean filterMandatory=false;
	private boolean subvisible=true;
	private boolean unicity=false;
	private boolean textarea=false;
	private boolean fkDataRef;
	private int superAttribute = 0;

	private String metatableReference="";

	private int fieldWidth;
	
	public CAttribute() {
	}

	public CAttribute(int id, String dataReference, boolean visible) {
		this.id = id;
		this.dataReference = dataReference;
		this.visible = visible;
	}

	public CAttribute(int id, CAttributetype CAttributetype,
			String dataReference, boolean visible, Set<CWindow> CWindows) {
		this.id = id;
		this.CAttributetype = CAttributetype;
		this.dataReference = dataReference;
		this.visible = visible;
		this.CWindows = CWindows;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_attributetype")
	public CAttributetype getCAttributetype() {
		return this.CAttributetype;
	}

	public void setCAttributetype(CAttributetype CAttributetype) {
		this.CAttributetype = CAttributetype;
	}

	@Column(name = "data_reference", nullable = false, length = 256)
	public String getDataReference() {
		return this.dataReference;
	}

	public void setDataReference(String dataReference) {
		this.dataReference = dataReference;
	}

	@Column(name = "visible", nullable = false)
	public boolean isVisible() {
		return this.visible;
	}

	public void setVisible(boolean visible) {
		this.visible = visible;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "c_window_windowattribute", schema = "public", joinColumns = { @JoinColumn(name = "id_attribute", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "id_window", nullable = false, updatable = false) })
	public Set<CWindow> getCWindows() {
		return this.CWindows;
	}

	public void setCWindows(Set<CWindow> CWindows) {
		this.CWindows = CWindows;
	}

	public CBusinessClass getEntity() {
		return entity;
	}

	public void setEntity(CBusinessClass entity) {
		this.entity = entity;
	}

	public String getAttribute() {
		return attribute;
	}

	public void setAttribute(String attribute) {
		this.attribute = attribute;
	}

	public boolean isKeyAttribute() {
		return isKeyAttribute;
	}

	public void setKeyAttribute(boolean isKeyAttribute) {
		this.isKeyAttribute = isKeyAttribute;
	}

	public boolean isReference() {
		return isReference;
	}

	public void setReference(boolean isReference) {
		this.isReference = isReference;
	}

	public String getDtoValue() {
		return dtoValue;
	}

	public void setDtoValue(String dtoValue) {
		this.dtoValue = dtoValue;
	}

	public boolean isCalculated() {
		return calculated;
	}

	public void setCalculated(boolean isCalculated) {
		this.calculated = isCalculated;
	}

	public String getFormula() {
		return formula;
	}

	public void setFormula(String formula) {
		this.formula = formula;
	}

	public boolean isMandatory() {
		return isMandatory;
	}

	public void setMandatory(boolean isMandatory) {
		this.isMandatory = isMandatory;
	}

	public String getTypeLabel() {
		return typeLabel;
	}

	public void setTypeLabel(String typeLabel) {
		this.typeLabel = typeLabel;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public boolean isMultiple() {
		return multiple;
	}

	public void setMultiple(boolean multiple) {
		this.multiple = multiple;
	}

	public int getDisplayOrder() {
		return dispalyOrder;
	}

	public void setDispalyOrder(int dispalyOrder) {
		this.dispalyOrder = dispalyOrder;
	}

	public boolean isAutoValue() {
		return isAutoValue;
	}

	public void setAutoValue(boolean isAutoValue) {
		this.isAutoValue = isAutoValue;
	}
	
	public String getName(){
		return this.attribute;
	}
	public void setName(String name){
		this.attribute = name;
	}

	public boolean isRequiresValidation() {
		return requiresValidation;
	}

	public void setRequiresValidation(boolean requiresValidation) {
		this.requiresValidation = requiresValidation;
	}

	public String getValidationFormula() {
		return validationFormula;
	}

	public void setValidationFormula(String validationFormula) {
		this.validationFormula = validationFormula;
	}

	public int getDispalyOrder() {
		return dispalyOrder;
	}
	public String getFileName() {
		return fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public String getFileExtension() {
		return fileExtension;
	}

	public void setFileExtension(String fileExtension) {
		this.fileExtension = fileExtension;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	public boolean isRappel() {
		return rappel;
	}

	public void setRappel(boolean rappel) {
		this.rappel = rappel;
	}

	public boolean isIndirectReference() {
		return indirectReference;
	}

	public void setIndirectReference(boolean indirectReference) {
		this.indirectReference = indirectReference;
	}

	public boolean isIndirectMtmKey() {
		return indirectMtmKey;
	}

	public void setIndirectMtmKey(boolean indirectMtmKey) {
		this.indirectMtmKey = indirectMtmKey;
	}

	public boolean isIndirectMtmValue() {
		return indirectMtmValue;
	}

	public void setIndirectMtmValue(boolean indirectMtmValue) {
		this.indirectMtmValue = indirectMtmValue;
	}

	public int getIndirectFunction() {
		return indirectFunction;
	}

	public void setIndirectFunction(int indirectFunction) {
		this.indirectFunction = indirectFunction;
	}

	public boolean isFilterEnabled() {
		return filterEnabled;
	}

	public void setFilterEnabled(boolean filterEnabled) {
		this.filterEnabled = filterEnabled;
	}

	public String getDefaultValue() {
		return defaultValue;
	}

	public void setDefaultValue(String defaultValue) {
		this.defaultValue = defaultValue;
	}

	public boolean isConditionalLayout() {
		return conditionalLayout;
	}

	public void setConditionalLayout(boolean conditionalLayout) {
		this.conditionalLayout = conditionalLayout;
	}

	public String getLockLabel() {
		return lockLabel;
	}

	public void setLockLabel(String lockLabel) {
		this.lockLabel = lockLabel;
	}

	public String getUnlockLabel() {
		return unlockLabel;
	}

	public void setUnlockLabel(String unlockLabel) {
		this.unlockLabel = unlockLabel;
	}

	public boolean isLockState() {
		return lockState;
	}

	public void setLockState(boolean lockState) {
		this.lockState = lockState;
	}

	public boolean isRegular() {
		return regular;
	}

	public void setRegular(boolean regular) {
		this.regular = regular;
	}

	public String getRegexp() {
		return regexp;
	}

	public void setRegexp(String regexp) {
		this.regexp = regexp;
	}

	public String getRegexpMessage() {
		return regexpMessage;
	}

	public void setRegexpMessage(String regexpMessage) {
		this.regexpMessage = regexpMessage;
	}

	public boolean isFilterMandatory() {
		return filterMandatory;
	}

	public void setFilterMandatory(boolean filterMandatory) {
		this.filterMandatory = filterMandatory;
	}

	public boolean isSubvisible() {
		return subvisible;
	}

	public void setSubvisible(boolean subvisible) {
		this.subvisible = subvisible;
	}

	public boolean isUnicity() {
		return unicity;
	}

	public void setUnicity(boolean unicity) {
		this.unicity = unicity;
	}

	public String getMetatableReference() {
		return metatableReference;
	}

	public void setMetatableReference(String metatableReference) {
		this.metatableReference = metatableReference;
	}

	/**
	 * @return the textarea
	 */
	public boolean isTextarea() {
		return textarea;
	}

	/**
	 * @param textarea the textarea to set
	 */
	public void setTextarea(boolean textarea) {
		this.textarea = textarea;
	}
	/**
	 * return true is dataref starts with fk_ and is not a reference
	 * @return
	 */
	public boolean isFkDataRef() {
		fkDataRef = !isReference() && getDataReference().startsWith("fk_");
		return fkDataRef;
	}

	/**
	 * @param fkDataRef the fkDataRef to set
	 */
	public void setFkDataRef(boolean fkDataRef) {
		this.fkDataRef = fkDataRef;
	}

	public int getSuperAttribute() {
		return superAttribute;
	}

	public void setSuperAttribute(int superAttribute) {
		this.superAttribute = superAttribute;
	}

	public int getFieldWidth() {
		return fieldWidth;
	}

	public void setFieldWidth(int fieldWidth) {
		this.fieldWidth = fieldWidth;
	}

	public int getFieldColumns(){
		return fieldWidth/8;
	}
}
