package fr.protogen.masterdata.model;

// Generated 12 oct. 2012 16:40:54 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CBusinessentity generated by hbm2java
 */
@Entity
@Table(name = "c_businessentity", schema = "public")
public class CBusinessentity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4240449014230878305L;
	private int id;
	private String dataReference;
	private boolean visible;
	private Set<CWindowattribute> CWindowattributes = new HashSet<CWindowattribute>(
			0);
	private Set<CoreAclElement> coreAclElements = new HashSet<CoreAclElement>(0);
	private Set<CWindow> CWindows = new HashSet<CWindow>(0);
	private Set<CBusinessClass> CBusinessclasses = new HashSet<CBusinessClass>(
			0);

	public CBusinessentity() {
	}

	public CBusinessentity(int id, String dataReference, boolean visible) {
		this.id = id;
		this.dataReference = dataReference;
		this.visible = visible;
	}

	public CBusinessentity(int id, String dataReference, boolean visible,
			Set<CWindowattribute> CWindowattributes,
			Set<CoreAclElement> coreAclElements, Set<CWindow> CWindows,
			Set<CBusinessClass> CBusinessclasses) {
		this.id = id;
		this.dataReference = dataReference;
		this.visible = visible;
		this.CWindowattributes = CWindowattributes;
		this.coreAclElements = coreAclElements;
		this.CWindows = CWindows;
		this.CBusinessclasses = CBusinessclasses;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "data_reference", nullable = false, length = 256)
	public String getDataReference() {
		return this.dataReference;
	}

	public void setDataReference(String dataReference) {
		this.dataReference = dataReference;
	}

	@Column(name = "visible", nullable = false)
	public boolean isVisible() {
		return this.visible;
	}

	public void setVisible(boolean visible) {
		this.visible = visible;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "CBusinessentity")
	public Set<CWindowattribute> getCWindowattributes() {
		return this.CWindowattributes;
	}

	public void setCWindowattributes(Set<CWindowattribute> CWindowattributes) {
		this.CWindowattributes = CWindowattributes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "CBusinessentity")
	public Set<CoreAclElement> getCoreAclElements() {
		return this.coreAclElements;
	}

	public void setCoreAclElements(Set<CoreAclElement> coreAclElements) {
		this.coreAclElements = coreAclElements;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "c_window_businessentity", schema = "public", joinColumns = { @JoinColumn(name = "id_businessentity", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "id_window", nullable = false, updatable = false) })
	public Set<CWindow> getCWindows() {
		return this.CWindows;
	}

	public void setCWindows(Set<CWindow> CWindows) {
		this.CWindows = CWindows;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "c_composite_bcalss", schema = "public", joinColumns = { @JoinColumn(name = "id_businessentity", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "id_businessclass", nullable = false, updatable = false) })
	public Set<CBusinessClass> getCBusinessclasses() {
		return this.CBusinessclasses;
	}

	public void setCBusinessclasses(Set<CBusinessClass> CBusinessclasses) {
		this.CBusinessclasses = CBusinessclasses;
	}

}
