package fr.protogen.masterdata.model;

// Generated 12 oct. 2012 16:40:54 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * CBusinessclass generated by hbm2java
 */
@Entity
@Table(name = "c_businessclass", schema = "public")
public class CBusinessClass implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private String dataReference;
	private boolean visible;
	private String appKey;
	private String name;
	private String description;
	private Set<CBusinessentity> CBusinessentities = new HashSet<CBusinessentity>(
			0);
	private List<CAttribute> attributes;
	private char userRestrict;
	private boolean storable;

	public CBusinessClass() {
	}

	public CBusinessClass(int id, String dataReference, boolean visible) {
		this.id = id;
		this.dataReference = dataReference;
		this.visible = visible;
	}

	public CBusinessClass(int id, String dataReference, boolean visible,
			Set<CBusinessentity> CBusinessentities) {
		this.id = id;
		this.dataReference = dataReference;
		this.visible = visible;
		this.CBusinessentities = CBusinessentities;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "data_reference", nullable = false, length = 256)
	public String getDataReference() {
		return this.dataReference;
	}

	public void setDataReference(String dataReference) {
		this.dataReference = dataReference;
	}

	@Column(name = "visible", nullable = false)
	public boolean isVisible() {
		return this.visible;
	}

	public void setVisible(boolean visible) {
		this.visible = visible;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "c_composite_bcalss", schema = "public", joinColumns = { @JoinColumn(name = "id_businessclass", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "id_businessentity", nullable = false, updatable = false) })
	public Set<CBusinessentity> getCBusinessentities() {
		return this.CBusinessentities;
	}

	public void setCBusinessentities(Set<CBusinessentity> CBusinessentities) {
		this.CBusinessentities = CBusinessentities;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public List<CAttribute> getAttributes() {
		return attributes;
	}

	public void setAttributes(List<CAttribute> attributes) {
		this.attributes = attributes;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getAppKey() {
		return appKey;
	}

	public void setAppKey(String appKey) {
		this.appKey = appKey;
	}

	public char getUserRestrict() {
		return userRestrict;
	}

	public void setUserRestrict(char userRestrict) {
		this.userRestrict = userRestrict;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("{id:");
		builder.append(id);
		builder.append(", dataReference:");
		builder.append("\"").append(dataReference).append("\"");
		builder.append(", visible:");
		builder.append(visible);
		builder.append(", appKey:");
		builder.append("\"").append(appKey).append("\"");
		builder.append(", name:");
		builder.append(name);
		builder.append(", description:");
		builder.append("\"").append(description).append("\"");
//		builder.append(", attributes:");
//		builder.append(attributes);
		builder.append(", userRestrict:");
		builder.append(userRestrict);
		builder.append("}");
 		return builder.toString();
	}

	public boolean isStorable() {
		return storable;
	}

	public void setStorable(boolean storable) {
		this.storable = storable;
	}
	
	

}
