package fr.protogen.masterdata.model;

// Generated 12 oct. 2012 16:40:54 by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CDocumentbutton generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "c_documentbutton", schema = "public")
public class CDocumentbutton implements java.io.Serializable {

	private int id;
	private CWindow CWindow;
	private MDocument MDocument;
	private String title;
	private String parameters;
	private List<ButtonParameter> listParam = new ArrayList<ButtonParameter>();
	private String description;

	public CDocumentbutton() {
	}

	public CDocumentbutton(int id, CWindow CWindow, MDocument MDocument) {
		this.id = id;
		this.CWindow = CWindow;
		this.MDocument = MDocument;
	}

	public CDocumentbutton(int id, CWindow CWindow, MDocument MDocument,
			String title, String parameters) {
		this.id = id;
		this.CWindow = CWindow;
		this.MDocument = MDocument;
		this.title = title;
		this.parameters = parameters;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_window", nullable = false)
	public CWindow getCWindow() {
		return this.CWindow;
	}

	public void setCWindow(CWindow CWindow) {
		this.CWindow = CWindow;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_document", nullable = false)
	public MDocument getMDocument() {
		return this.MDocument;
	}

	public void setMDocument(MDocument MDocument) {
		this.MDocument = MDocument;
	}

	@Column(name = "title", length = 256)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "parameters")
	public String getParameters() {
		return this.parameters;
	}

	public void setParameters(String parameters) {
		this.parameters = parameters;
	}

	public List<ButtonParameter> getListParam() {
		return listParam;
	}

	public void setListParam(List<ButtonParameter> listParam) {
		this.listParam = listParam;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
