package fr.protogen.masterdata.model;

// Generated 12 oct. 2012 16:40:54 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CoreAclElement generated by hbm2java
 */
@Entity
@Table(name = "core_acl_element", schema = "public")
public class CoreAclElement implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2564824134566381613L;
	private int id;
	private CoreRole coreRole;
	private CWindow CWindow;
	private SScreensequence SScreensequence;
	private CBusinessentity CBusinessentity;
	private Integer accessMode;

	public CoreAclElement() {
	}

	public CoreAclElement(int id, CoreRole coreRole) {
		this.id = id;
		this.coreRole = coreRole;
	}

	public CoreAclElement(int id, CoreRole coreRole, CWindow CWindow,
			SScreensequence SScreensequence, CBusinessentity CBusinessentity,
			Integer accessMode) {
		this.id = id;
		this.coreRole = coreRole;
		this.CWindow = CWindow;
		this.SScreensequence = SScreensequence;
		this.CBusinessentity = CBusinessentity;
		this.accessMode = accessMode;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idrole", nullable = false)
	public CoreRole getCoreRole() {
		return this.coreRole;
	}

	public void setCoreRole(CoreRole coreRole) {
		this.coreRole = coreRole;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idscreen")
	public CWindow getCWindow() {
		return this.CWindow;
	}

	public void setCWindow(CWindow CWindow) {
		this.CWindow = CWindow;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idsequence")
	public SScreensequence getSScreensequence() {
		return this.SScreensequence;
	}

	public void setSScreensequence(SScreensequence SScreensequence) {
		this.SScreensequence = SScreensequence;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "identity")
	public CBusinessentity getCBusinessentity() {
		return this.CBusinessentity;
	}

	public void setCBusinessentity(CBusinessentity CBusinessentity) {
		this.CBusinessentity = CBusinessentity;
	}

	@Column(name = "accessMode")
	public Integer getAccessMode() {
		return this.accessMode;
	}

	public void setAccessMode(Integer accessMode) {
		this.accessMode = accessMode;
	}

}
