package fr.protogen.masterdata.model;

// Generated 12 oct. 2012 16:40:54 by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CoreUser generated by hbm2java
 */
@Entity
@Table(name = "core_user", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "login"))
public class CoreUser implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1761124908933666428L;
	private int id;
	private CoreRole coreRole;
	private String firstName;
	private String lastName;
	private String tel;
	private String email;
	private String adress;
	private String login;
	private String password;
	private String appKey;
	private String userTheme="THEME:ROUGE";
	private String themeColor="css/colors.css?v=1";
	private String themeStyle="css/style.css?v=1";
	private String soptions="";
	private List<SMenuitem> options = new ArrayList<SMenuitem>();
	private COrganization organization;
	private int orgInstance;
	private int boundEntity;
	private GOrganization originalOrganization;
	private String photo = "";
	private CoreProfil profil;
	private String language="";
	
	public CoreUser() {
	}

	public CoreUser(int id, CoreRole coreRole, String login) {
		this.id = id;
		this.coreRole = coreRole;
		this.login = login;
	}

	public CoreUser(int id, CoreRole coreRole, String firstName,
			String lastName, String tel, String email, String adress,
			String login, String password) {
		this.id = id;
		this.coreRole = coreRole;
		this.firstName = firstName;
		this.lastName = lastName;
		this.tel = tel;
		this.email = email;
		this.adress = adress;
		this.login = login;
		this.password = password;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idRole", nullable = false)
	public CoreRole getCoreRole() {
		return this.coreRole;
	}

	public void setCoreRole(CoreRole coreRole) {
		this.coreRole = coreRole;
	}

	@Column(name = "firstName", length = 256)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "lastName", length = 256)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "tel", length = 32)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "email", length = 32)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "adress")
	public String getAdress() {
		return this.adress;
	}

	public void setAdress(String adress) {
		this.adress = adress;
	}

	@Column(name = "login", unique = true, nullable = false, length = 128)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "password", length = 256)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getAppKey() {
		return appKey;
	}

	public void setAppKey(String appKey) {
		this.appKey = appKey;
	}

	public String getUserTheme() {
		return userTheme;
	}

	public void setUserTheme(String userTheme) {
		this.userTheme = userTheme;
	}

	public List<SMenuitem> getOptions() {
		return options;
	}

	public void setOptions(List<SMenuitem> options) {
		this.options = options;
	}

	public String getSoptions() {
		return soptions;
	}

	public void setSoptions(String soptions) {
		this.soptions = soptions;
	}

	public COrganization getOrganization() {
		return organization;
	}

	public void setOrganization(COrganization organization) {
		this.organization = organization;
	}

	public int getOrgInstance() {
		return orgInstance;
	}

	public void setOrgInstance(int orgInstance) {
		this.orgInstance = orgInstance;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	public int getBoundEntity() {
		return boundEntity;
	}

	public void setBoundEntity(int boundEntity) {
		this.boundEntity = boundEntity;
	}

	public GOrganization getOriginalOrganization() {
		return originalOrganization;
	}

	public void setOriginalOrganization(GOrganization originalOrganization) {
		this.originalOrganization = originalOrganization;
	}

	public String getThemeColor() {
		return themeColor;
	}

	public void setThemeColor(String themeColor) {
		this.themeColor = themeColor;
	}

	public String getThemeStyle() {
		return themeStyle;
	}

	public void setThemeStyle(String themeStyle) {
		this.themeStyle = themeStyle;
	}

	public String getPhoto() {
		return photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	public CoreProfil getProfil() {
		return profil;
	}

	public void setProfil(CoreProfil profil) {
		this.profil = profil;
	}

	public String getLanguage() {
		return language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}


}
