package fr.protogen.masterdata.model;

// Generated 12 oct. 2012 16:40:54 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CWindowtype generated by hbm2java
 */
@Entity
@Table(name = "c_windowtype", schema = "public")
public class CWindowtype implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 766861560725307682L;
	private int id;
	private String type;
	private Set<CWindow> CWindows = new HashSet<CWindow>(0);

	public CWindowtype() {
	}

	public CWindowtype(int id, String type) {
		this.id = id;
		this.type = type;
	}

	public CWindowtype(int id, String type, Set<CWindow> CWindows) {
		this.id = id;
		this.type = type;
		this.CWindows = CWindows;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "type", nullable = false, length = 128)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "CWindowtype")
	public Set<CWindow> getCWindows() {
		return this.CWindows;
	}

	public void setCWindows(Set<CWindow> CWindows) {
		this.CWindows = CWindows;
	}

}
