package fr.protogen.masterdata.model;

// Generated 12 oct. 2012 16:40:54 by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MAction generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "m_action", schema = "public")
public class MAction implements java.io.Serializable {

	private int id;
	private String title;
	private String code;
	private Set<CActionbutton> CActionbuttons = new HashSet<CActionbutton>(0);
	private List<CActionArgument> arguments = new ArrayList<CActionArgument>(0);
	private MPostAction postAction;

	public MAction() {
	}

	public MAction(int id, String title, String code) {
		this.id = id;
		this.title = title;
		this.code = code;
	}

	public MAction(int id, String title, String code,
			Set<CActionbutton> CActionbuttons) {
		this.id = id;
		this.title = title;
		this.code = code;
		this.CActionbuttons = CActionbuttons;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "title", nullable = false, length = 256)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "code", nullable = false)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "MAction")
	public Set<CActionbutton> getCActionbuttons() {
		return this.CActionbuttons;
	}

	public void setCActionbuttons(Set<CActionbutton> CActionbuttons) {
		this.CActionbuttons = CActionbuttons;
	}

	public List<CActionArgument> getArguments() {
		return arguments;
	}

	public void setArguments(List<CActionArgument> arguments) {
		this.arguments = arguments;
	}

	public MPostAction getPostAction() {
		return postAction;
	}

	public void setPostAction(MPostAction postAction) {
		this.postAction = postAction;
	}

}
