package fr.protogen.masterdata.model;

// Generated 12 oct. 2012 16:40:54 by Hibernate Tools 3.4.0.CR1

import java.io.InputStream;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * SApplication generated by hbm2java
 */
@Entity
@Table(name = "s_application", schema = "public")
public class SApplication implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1510134181669087113L;
	private int id;
	private String version;
	private String projectName;
	private String author;
	private String description;
	private String licence;
	private InputStream logo;
	private String appKey;
	
	//	Social networks
	private String fbID="343336852365729";
	private String fbUrl="https://www.facebook.com/PhoenixAccess";
	private String twID="403187362319970304";
	private String twUrl="https://twitter.com/InfodiumMaroc";
	private String twitter="@InfodiumMaroc";
	
	public String getAuthor() {
		return author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getLicence() {
		return licence;
	}

	public void setLicence(String licence) {
		this.licence = licence;
	}

	public InputStream getLogo() {
		return logo;
	}

	public void setLogo(InputStream logo) {
		this.logo = logo;
	}

	private Set<SMainwindow> SMainwindows = new HashSet<SMainwindow>(0);

	public SApplication() {
	}

	public SApplication(int id, String projectName) {
		this.id = id;
		this.projectName = projectName;
	}

	public SApplication(int id, String projectName,
			Set<SMainwindow> SMainwindows) {
		this.id = id;
		this.projectName = projectName;
		this.SMainwindows = SMainwindows;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Version
	@Column(name = "version", nullable = false, length = 16)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@Column(name = "project_name", nullable = false, length = 256)
	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "SApplication")
	public Set<SMainwindow> getSMainwindows() {
		return this.SMainwindows;
	}

	public void setSMainwindows(Set<SMainwindow> SMainwindows) {
		this.SMainwindows = SMainwindows;
	}

	public String getAppKey() {
		return appKey;
	}

	public void setAppKey(String appKey) {
		this.appKey = appKey;
	}

	public String getFbID() {
		return fbID;
	}

	public void setFbID(String fbID) {
		this.fbID = fbID;
	}

	public String getFbUrl() {
		return fbUrl;
	}

	public void setFbUrl(String fbUrl) {
		this.fbUrl = fbUrl;
	}

	public String getTwID() {
		return twID;
	}

	public void setTwID(String twID) {
		this.twID = twID;
	}

	public String getTwUrl() {
		return twUrl;
	}

	public void setTwUrl(String twUrl) {
		this.twUrl = twUrl;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	public String getTwitter() {
		return twitter;
	}

	public void setTwitter(String twitter) {
		this.twitter = twitter;
	}

}
