package fr.protogen.masterdata.model;

// Generated 12 oct. 2012 16:40:54 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SMainwindow generated by hbm2java
 */
@Entity
@Table(name = "s_mainwindow", schema = "public")
public class SMainwindow implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4863734858986027946L;
	private int id;
	private SApplication SApplication;
	private byte[] logo;
	private String applicationTitle;

	public SMainwindow() {
	}

	public SMainwindow(int id) {
		this.id = id;
	}

	public SMainwindow(int id, SApplication SApplication, byte[] logo,
			String applicationTitle) {
		this.id = id;
		this.SApplication = SApplication;
		this.logo = logo;
		this.applicationTitle = applicationTitle;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "s_application_id")
	public SApplication getSApplication() {
		return this.SApplication;
	}

	public void setSApplication(SApplication SApplication) {
		this.SApplication = SApplication;
	}

	@Column(name = "logo")
	public byte[] getLogo() {
		return this.logo;
	}

	public void setLogo(byte[] logo) {
		this.logo = logo;
	}

	@Column(name = "application_title", length = 256)
	public String getApplicationTitle() {
		return this.applicationTitle;
	}

	public void setApplicationTitle(String applicationTitle) {
		this.applicationTitle = applicationTitle;
	}

}
