package fr.protogen.masterdata.model;

// Generated 12 oct. 2012 16:40:54 by Hibernate Tools 3.4.0.CR1

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SMenuitem generated by hbm2java
 */
@Entity
@Table(name = "s_menuitem", schema = "public")
public class SMenuitem implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8773804125899506100L;
	private int id;
	private SScreensequence SScreensequence;
	private CWindow window;
	private String title;
	private boolean isParent;
	private String parentName;
	private Integer idParent;
	private SMenuitem parent;
	private String appKey;
	private int rubrique;
	private List<SMenuitem> subs;
	private int menuSize;

	public boolean isParent() {
		return isParent;
	}

	public void setParent(boolean isParent) {
		this.isParent = isParent;
	}

	public SMenuitem getParent() {
		return parent;
	}

	public SMenuitem() {
	}

	public SMenuitem(int id, String title, boolean isParent) {
		this.id = id;
		this.title = title;
		this.isParent = isParent;
	}

	public SMenuitem(int id, SScreensequence SScreensequence, String title,
			boolean isParent, Integer idParent) {
		this.id = id;
		this.SScreensequence = SScreensequence;
		this.title = title;
		this.isParent = isParent;
		this.idParent = idParent;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_screensequence")
	public SScreensequence getSScreensequence() {
		return this.SScreensequence;
	}

	public void setSScreensequence(SScreensequence SScreensequence) {
		this.SScreensequence = SScreensequence;
	}

	@Column(name = "title", nullable = false, length = 128)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "isParent", nullable = false)
	public boolean isIsParent() {
		return this.isParent;
	}

	public void setIsParent(boolean isParent) {
		this.isParent = isParent;
	}

	@Column(name = "id_parent")
	public Integer getIdParent() {
		return this.idParent;
	}

	public void setIdParent(Integer idParent) {
		this.idParent = idParent;
	}

	public void setParent(SMenuitem parent) {
		// TODO Auto-generated method stub
		this.parent = parent;
		this.idParent = parent.id;
	}

	public String getAppKey() {
		return appKey;
	}

	public void setAppKey(String appKey) {
		this.appKey = appKey;
	}

	public CWindow getWindow() {
		return window;
	}

	public void setWindow(CWindow window) {
		this.window = window;
	}

	public String getParentName() {
		return parentName;
	}

	public void setParentName(String parentName) {
		this.parentName = parentName;
	}

	public int getRubrique() {
		return rubrique;
	}

	public void setRubrique(int rubrique) {
		this.rubrique = rubrique;
	}

	public List<SMenuitem> getSubs() {
		return subs;
	}

	public void setSubs(List<SMenuitem> subs) {
		this.subs = subs;
	}

	public int getMenuSize() {
		return subs.size();
	}

	public void setMenuSize(int menuSize) {
		this.menuSize = menuSize;
	}

}
