package fr.protogen.masterdata.model;

// Generated 12 oct. 2012 16:40:54 by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SScreensequence generated by hbm2java
 */
@Entity
@Table(name = "s_screensequence", schema = "public")
public class SScreensequence implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2590985390440964037L;
	private int id;
	private String title;
	private String description;
	private String appKey;
	private Set<CoreAclElement> coreAclElements = new HashSet<CoreAclElement>(0);
	private Set<SMenuitem> SMenuitems = new HashSet<SMenuitem>(0);
	private List<CWindow> windows = new ArrayList<CWindow>();

	public SScreensequence() {
	}

	public SScreensequence(int id, String title) {
		this.id = id;
		this.title = title;
	}

	public SScreensequence(int id, String title,
			Set<CoreAclElement> coreAclElements, Set<SMenuitem> SMenuitems) {
		this.id = id;
		this.title = title;
		this.coreAclElements = coreAclElements;
		this.SMenuitems = SMenuitems;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "title", nullable = false, length = 128)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "SScreensequence")
	public Set<CoreAclElement> getCoreAclElements() {
		return this.coreAclElements;
	}

	public void setCoreAclElements(Set<CoreAclElement> coreAclElements) {
		this.coreAclElements = coreAclElements;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "SScreensequence")
	public Set<SMenuitem> getSMenuitems() {
		return this.SMenuitems;
	}

	public void setSMenuitems(Set<SMenuitem> SMenuitems) {
		this.SMenuitems = SMenuitems;
	}

	public List<CWindow> getWindows() {
		return windows;
	}

	public void setWindows(List<CWindow> windows) {
		this.windows = windows;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getAppKey() {
		return appKey;
	}

	public void setAppKey(String appKey) {
		this.appKey = appKey;
	}

}
