package fr.protogen.masterdata.model;


import java.util.ArrayList;
import java.util.List;

/**
 * CWindowtype generated by hbm2java
 */
public class WindowModule implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 766861560725307682L;
	private int id;
	private String title;
	private List<CWindow> CWindows = new ArrayList<CWindow>(0);

	public WindowModule() {
	}

	public WindowModule(int id, String title) {
		this.id = id;
		this.title=title;
	}

	public WindowModule(int id, String title, List<CWindow> CWindows) {
		this.id = id;
		this.title=title;
		this.CWindows = CWindows;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public List<CWindow> getCWindows() {
		return CWindows;
	}

	public void setCWindows(List<CWindow> cWindows) {
		CWindows = cWindows;
	}

	

}
